from fastapi import APIRouter

from app.api.v1.endpoints import actions, agent, agent_commands, agent_config, agent_packages, alerts, audit, auth, bootstrap, clients, deployments, devices, enrollment_bootstrap, enrollment_tokens, groups, health, operator_scopes, install, operators, packages, platform, remote_support, teams, trusted_domains, vault

api_router = APIRouter()
api_router.include_router(health.router, prefix="", tags=["health"])
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(agent.router, prefix="/agent", tags=["agent"])
api_router.include_router(bootstrap.router, prefix="/bootstrap", tags=["bootstrap"])
api_router.include_router(clients.router, prefix="/clients", tags=["clients"])
api_router.include_router(trusted_domains.router, prefix="/trusted-domains", tags=["trusted-domains"])
api_router.include_router(devices.router, prefix="/devices", tags=["devices"])
api_router.include_router(groups.router, prefix="/groups", tags=["groups"])
api_router.include_router(deployments.router, prefix="/deployments", tags=["deployments"])
api_router.include_router(alerts.router, prefix="/alerts", tags=["alerts"])
api_router.include_router(enrollment_tokens.router, prefix="/enrollment-tokens", tags=["enrollment-tokens"])
api_router.include_router(enrollment_bootstrap.router, prefix="/enrollment-bootstrap", tags=["enrollment-bootstrap"])
api_router.include_router(agent_packages.router, prefix="/agent-packages", tags=["agent-packages"])
api_router.include_router(packages.router, prefix="/packages", tags=["packages"])
api_router.include_router(operators.router, prefix="/operators", tags=["operators"])
api_router.include_router(operator_scopes.router, prefix="/operators", tags=["operator-scopes"])
api_router.include_router(actions.router, prefix="", tags=["actions"])
api_router.include_router(agent_commands.router, prefix="", tags=["agent-commands"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(remote_support.router, prefix="/remote-support", tags=["remote-support"])
api_router.include_router(teams.router, prefix="/teams", tags=["teams"])
api_router.include_router(agent_config.router, prefix="/agent-config", tags=["agent-config"])
api_router.include_router(platform.router, prefix="/platform", tags=["platform"])
api_router.include_router(install.router, prefix="/install", tags=["install"])
api_router.include_router(vault.router, prefix="/vault", tags=["vault"])
