"""Phase 2 — Linux installer endpoint (flag-gated)."""

from types import SimpleNamespace

from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.api.v1.endpoints import install as install_endpoint
from app.core.config import settings


def _client(monkeypatch, flag_on: bool) -> TestClient:
    monkeypatch.setattr(settings, "FEATURE_PLATFORM_CORE", flag_on)
    monkeypatch.setattr(settings, "FEATURE_LINUX", flag_on)
    app = FastAPI()
    app.include_router(install_endpoint.router, prefix="/api/v1/install")
    return TestClient(app)


def test_404_when_flag_off(monkeypatch):
    client = _client(monkeypatch, flag_on=False)
    resp = client.get("/api/v1/install/linux", params={"token": "TKN-1"})
    assert resp.status_code == 404


def test_script_served_when_flag_on(monkeypatch):
    client = _client(monkeypatch, flag_on=True)
    resp = client.get("/api/v1/install/linux", params={"token": "TKN-ABC"})
    assert resp.status_code == 200
    body = resp.text
    assert body.startswith("#!/usr/bin/env bash")
    assert "TOKEN=\"TKN-ABC\"" in body
    assert "linux-${ARCH}/download" in body
    assert "techi-agent" in body
    assert "install --config" in body


def test_token_required(monkeypatch):
    client = _client(monkeypatch, flag_on=True)
    resp = client.get("/api/v1/install/linux")
    assert resp.status_code == 422


# ── re-runnable installer (RISK-INSTALL-001) ─────────────────────────────── #
#
# The original script could only ever install onto a clean host. It wrote the
# download straight over /usr/local/bin/techi-agent, which the kernel refuses
# while that binary is running (ETXTBSY), so curl exited 23 and `set -euo
# pipefail` aborted — reproduced on device 729, 2026-08-05. Worse, had the
# download succeeded it would have overwritten the config that holds agent_id
# and device_id, forcing a re-enrolment on an already-known machine.


def _script(monkeypatch) -> str:
    return _client(monkeypatch, flag_on=True).get(
        "/api/v1/install/linux", params={"token": "TKN-ABC"}
    ).text


def test_generated_script_is_valid_bash(monkeypatch, tmp_path):
    """The script is generated by string interpolation; a stray brace would
    only ever be discovered on a customer's server."""
    import shutil
    import subprocess

    bash = shutil.which("bash")
    if bash is None:
        import pytest
        pytest.skip("bash not available")

    path = tmp_path / "install.sh"
    path.write_text(_script(monkeypatch))
    result = subprocess.run([bash, "-n", str(path)], capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_binary_is_not_downloaded_over_the_running_executable(monkeypatch):
    body = _script(monkeypatch)
    assert '-o "${TMP_BIN}"' in body, "download must land in a temp file"
    assert '-o "${BIN_PATH}"' not in body, (
        "writing the download straight onto the running binary is what made "
        "this installer unusable on any host that already had the agent"
    )


def test_service_is_stopped_before_the_binary_is_replaced(monkeypatch):
    body = _script(monkeypatch)
    stop = body.index('systemctl stop "${SERVICE}"')
    install = body.index('install -m 0755')
    assert stop < install, "the binary cannot be replaced while it is running"


def test_download_happens_before_the_service_is_stopped(monkeypatch):
    """A failed download must cost no downtime."""
    body = _script(monkeypatch)
    assert body.index("curl -fsSL") < body.index('systemctl stop "${SERVICE}"')


def test_an_existing_configuration_is_never_overwritten(monkeypatch):
    """agent_id/device_id live in that file; rewriting it re-enrols a machine
    the platform already knows (RISK-IDENT-001)."""
    body = _script(monkeypatch)
    assert 'if [ -f "${CONFIG_PATH}" ]; then' in body
    assert "device identity preserved" in body
    config_guard = body.index('if [ -f "${CONFIG_PATH}" ]; then')
    config_write = body.index('cat > "${CONFIG_PATH}"')
    assert config_guard < config_write, "the write must sit in the else branch"


def test_enrollment_token_is_only_passed_when_not_yet_enrolled(monkeypatch):
    body = _script(monkeypatch)
    assert '"${BIN_PATH}" install --config "${CONFIG_PATH}"\n' in body, (
        "an enrolled host must be installed without a token, so the token is "
        "not baked into the systemd unit for no reason"
    )
    assert '--enrollment-token "${TOKEN}"' in body


def test_checksum_is_published_and_enforced(monkeypatch):
    body = _script(monkeypatch)
    assert "EXPECTED_SHA256=" in body
    assert "Checksum mismatch - refusing to install." in body


def test_previous_binary_is_backed_up(monkeypatch):
    body = _script(monkeypatch)
    assert 'BACKUP="${BIN_PATH}.bak-' in body
    assert "restoring previous binary" in body
