from datetime import timedelta
from types import SimpleNamespace

import pytest
from fastapi import HTTPException

from app.api.v1.endpoints.remote_support import (
    _connect_url_response_for_device,
    _build_connect_url,
)
from app.core.time import utcnow


def test_connect_url_includes_encoded_per_device_password(monkeypatch):
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": True},
    )
    assert _build_connect_url("294 938 618", "Durres.12!") == (
        "techiremotesupport://294%20938%20618?password=Durres.12%21"
    )


def test_connect_url_omits_password_when_feature_disabled(monkeypatch):
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": False},
    )
    assert _build_connect_url("294938618", "anything") == "techiremotesupport://294938618"


def test_connect_url_omits_blank_password(monkeypatch):
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": True},
    )
    assert _build_connect_url("294938618", "   ") == "techiremotesupport://294938618"


def test_connect_url_uses_per_device_password(monkeypatch):
    """The connect URL must embed the device's own password, generated by the
    per-device service — never a fleet-wide shared value."""
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": True},
    )

    class FakePwSvc:
        def __init__(self, db):
            pass

        def get_or_create(self, device):
            return "UniquePerDevice9"

    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.RemoteSupportPasswordService", FakePwSvc
    )
    device = SimpleNamespace(id=590, rustdesk_id="486641675", agent_version="2.1.5")

    response = _connect_url_response_for_device(device, db=None)

    assert response.device_id == 590
    assert response.connect_url == "techiremotesupport://486641675?password=UniquePerDevice9"


def test_connect_url_allows_stale_agent_heartbeat_when_remote_id_exists(monkeypatch):
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": False},
    )

    class FakePwSvc:
        def __init__(self, db):
            pass

        def get_or_create(self, device):
            return "irrelevant"

    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.RemoteSupportPasswordService", FakePwSvc
    )
    device = SimpleNamespace(
        id=590,
        rustdesk_id="486641675",
        agent_version="2.1.5",
        last_seen=utcnow() - timedelta(hours=3),
        rustdesk_status="running",
        rustdesk_install_status="installed",
    )

    response = _connect_url_response_for_device(device, db=None)

    assert response.device_id == 590
    assert response.techi_remote_id == "486641675"
    assert response.connect_url == "techiremotesupport://486641675"


def test_connect_url_still_rejects_missing_remote_id():
    device = SimpleNamespace(id=590, rustdesk_id="")

    with pytest.raises(HTTPException) as exc:
        _connect_url_response_for_device(device, db=None)

    assert exc.value.status_code == 422


def test_connect_url_falls_back_to_legacy_password_for_old_agent(monkeypatch):
    """Agents < 2.1.5 still hold the legacy shared password; connect must use
    it during the rollout so remote access does not break fleet-wide."""
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": True},
    )
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.settings.RUSTDESK_DEFAULT_PASSWORD", "Durres.12"
    )

    class BoomPwSvc:
        def __init__(self, db):
            pass

        def get_or_create(self, device):
            raise AssertionError("must not generate per-device password for old agent")

    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.RemoteSupportPasswordService", BoomPwSvc
    )
    device = SimpleNamespace(id=590, rustdesk_id="486641675", agent_version="2.1.4")

    response = _connect_url_response_for_device(device, db=None)
    assert response.connect_url == "techiremotesupport://486641675?password=Durres.12"


def test_connect_url_uses_per_device_for_215_agent(monkeypatch):
    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.agent_config_service.get_policy",
        lambda: {"remote_support_managed_password_enabled": True},
    )

    class FakePwSvc:
        def __init__(self, db):
            pass

        def get_or_create(self, device):
            return "PerDevice12345"

    monkeypatch.setattr(
        "app.api.v1.endpoints.remote_support.RemoteSupportPasswordService", FakePwSvc
    )
    device = SimpleNamespace(id=590, rustdesk_id="486641675", agent_version="2.1.5")

    response = _connect_url_response_for_device(device, db=None)
    assert response.connect_url == "techiremotesupport://486641675?password=PerDevice12345"
