#!/usr/bin/env python3

from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
launcher = (ROOT / "remote-support-macos/Launcher.swift").read_text(encoding="utf-8")
darwin = (ROOT / "remote-support-bridge/platform_darwin.go").read_text(encoding="utf-8")
protocol = (ROOT / "remote-support-bridge/protocol.go").read_text(encoding="utf-8")
builder = (ROOT / "scripts/build-macos-remote-support.sh").read_text(encoding="utf-8")
combined = "\n".join((launcher, darwin, protocol, builder))


def fail(message: str) -> None:
    print(f"macOS Remote Support security check failed: {message}", file=sys.stderr)
    raise SystemExit(1)


required = (
    "Bundle.main.bundleURL.appendingPathComponent",
    "process.standardInput = input",
    "input.fileHandleForWriting.write(data)",
    'arguments: ["--stdin-uri"]',
    "CFBundleURLSchemes:0 string techiremotesupport",
    "CFBundleIdentifier",
    "al.techi.remote-support",
    "performPeerConfigHandoff",
    "restrictFileMode",
    "cleanupStaleHandoffs",
)
for value in required:
    if value not in combined:
        fail(f"missing contract marker: {value}")

for forbidden in (
    "?password=",
    "&password=",
    "--password",
    "password=",
    "osascript",
    "UserDefaults",
    "SecItemAdd",
    "xattr -dr",
    "spctl --master-disable",
):
    if forbidden.lower() in combined.lower():
        fail(f"forbidden credential or platform behavior: {forbidden}")

if re.search(r"exec\.Command\([^\n]*password", darwin, re.IGNORECASE):
    fail("password reaches macOS process command construction")
if 'exec.Command(clientPath, "--connect", remoteID)' not in darwin:
    fail("macOS client command is not the approved ID-only form")
if launcher.count("CFBundleURLSchemes"):
    fail("URL scheme metadata must be generated by the canonical build script")

print("macOS remote-support connect security check: PASS")
